title: Fart Depot dot Biz
email: hello@fartdepot.biz
description: stuff that i drew and i wrote, because if it's not posted somewhere, did i really make it?
locale: en_US
baseurl: ""
url: "http://fartdepot.biz"

twitter_username: fartdepot

permalink: /:categories/:year/:month/:day/

lsi: true

markdown: kramdown
safe: false

pagination:
  enabled: true
  title: ':title - page :num'
  per_page: 20
  sort_reverse: true
  trail:
    before: 2
    after: 2

autopages:
  enabled: true
  collections:
    enabled: false
  tags:
    enabled: false
  categories:
    layouts:
      - 'autopage_category.html'
    permalink: '/:cat/'

plugins:
  - jekyll-feed

sass:
  sass_dir: _sass
  style: compressed
  
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
